### ISSUE TITLE
cergyk - Cannot pause transfers on FootiumClub because of wrong inherited class

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#171]
cergyk

medium

# Cannot pause transfers on FootiumClub because of wrong inherited class

## Summary
Pausing FootiumClub only pauses mints and not transfers.

## Vulnerability Detail
Since FootiumClub inherits ERC721Upgradeable class, it is not aware of the pausable abilities of the child contract:
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumClub.sol#L16

When the admin pauses the contract, only methods explicitely using `whenNotPaused` modifier would be impacted, in this case only `safeMint`:
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumClub.sol#L56-L69

This would not pause transferability of the tokens, which would still allow them to be traded on secondary, which may not be desirable when trying to work out an emergency.

## Impact
Pausing the NFT contract still enables transfers, and activity on secondary.

## Tool used
Manual Review

## Recommendation
FootiumClub should inherit ERC721PausableUpgradeable class of openzeppelin-contracts-upgradeable, implementing a check on paused in `_beforeTokenTransfer` hook:
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/dd8ca8adc47624c5c5e2f4d412f5f421951dcc25/contracts/token/ERC721/extensions/ERC721PausableUpgradeable.sol#L37-L46

**Comment by eliteWalrus4164** [comment]
Escalate for 10 USDC

One may argue that this is a design choice, but in the case of FootiumClub it is a really weird one, since only the owner is allowed to mint through the `FootiumMinter` contract.

This makes the pausability of the contract completely useless, since the only functonality paused in the case of an emergency is the minting, which is accessible only by the owner.

There is clearly an inconsistency in this particular case, I would recommend either using `ERC721PausableUpgradeable` or remove `Pausable` to avoid confusion

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> One may argue that this is a design choice, but in the case of FootiumClub it is a really weird one, since only the owner is allowed to mint through the `FootiumMinter` contract.
> 
> This makes the pausability of the contract completely useless, since the only functonality paused in the case of an emergency is the minting, which is accessible only by the owner.
> 
> There is clearly an inconsistency in this particular case, I would recommend either using `ERC721PausableUpgradeable` or remove `Pausable` to avoid confusion

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Impact is not severity enough to be considered as a medium

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Given that this is and admin role based function the impact can be considered low.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> Given that this is and admin role based function the impact can be considered low. 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
