### ISSUE TITLE
shaka - Prize merkle tree amount and recipient can be calculated incorrectly

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#214]
shaka

medium

# Prize merkle tree amount and recipient can be calculated incorrectly

## Summary

Prize merkle tree amount and recipient can be calculated incorrectly.

## Vulnerability Detail

In the [documentation](https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/technical-docs/FootiumPrizeDistributor.md#claimerc20prizeaddress-_to-ierc20upgradeable-_token-uint256-_amount-bytes32-calldata-_proof) of `FootiumPrizeDistributor`'s `claimERC20Prize` and `claimETHPrize` functions it says `The function checks to see whether the function caller owns the club that they're claiming prizes for`. However, this check does not exist in the code:

```solidity
144:     function claimETHPrize(
145:         address _to,
146:         uint256 _amount,
147:         bytes32[] calldata _proof
148:     ) external whenNotPaused nonReentrant {
149:         if (_to != msg.sender) {
150:             revert InvalidAccount();
151:         }
152: 
153:         if (
154:             !MerkleProofUpgradeable.verify(
155:                 _proof,
156:                 ethMerkleRoot,
157:                 keccak256(abi.encodePacked(_to, _amount))
158:             )
159:         ) {
160:             revert InvalidETHMerkleProof();
161:         }
162: 
163:         uint256 value = _amount - totalETHClaimed[_to];
164: 
165:         if (value > 0) {
166:             totalETHClaimed[_to] += value;
167: 
168:             (bool sent, ) = _to.call{value: value}("");
169:             if (!sent) {
170:                 revert FailedToSendETH(value);
171:             }
172:         }
173: 
174:         emit ClaimETH(_to, value);
175:     }
```

## Impact

In case the owner of the club changes, to ensure that the new owner will be able to claim future rewards, users need to rely on the off-chain merkle tree generation accounting for the change in ownership. If that change is not detected, the merkle tree will be granting the price to the old owner.

In the merkle tree generation, it will have to be accounted also the possibility of an address owning more than one club, so that `_amount` is the summation of the prizes for all clubs owned in the present or the past.

Given that tracking all these situations off-chain can be prone to many accounting errors, the ownership of the club should be abstracted away and the prizes be associated to the club instead.

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L97-L175

## Tool used

Manual Review.

## Recommendation

Instead of including the `_to` address in the merkle tree, include the club id and check that `msg.sender` is the owner of the club.

**Comment by eliteWalrus4164** [comment]
Escalate for 10 USDC

This is unrelated to #300, which is about 64 bytes merkle leaf nodes clashing with internal nodes

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is unrelated to #300, which is about 64 bytes merkle leaf nodes clashing with internal nodes 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by logiclogue** [comment]
Sponsor commenting here and confirming this issue. `_to` needs to be the escrow address of the club to avoid this issue

**Comment by ctf-sec** [comment]
Given the sponsor confirmed tag, as stated by the impact

> In case the owner of the club changes, to ensure that the new owner will be able to claim future rewards, users need to rely on the off-chain merkle tree generation accounting for the change in ownership. If that change is not detected, the merkle tree will be granting the price to the old owner.

In the merkle tree generation, it will have to be accounted also the possibility of an address owning more than one club, so that _amount is the summation of the prizes for all clubs owned in the present or the past.

Given that tracking all these situations off-chain can be prone to many accounting errors, the ownership of the club should be abstracted away and the prizes be associated to the club instead.

**The report deserves to be a unique valid medium**

**Comment by ctf-sec** [comment]
https://github.com/sherlock-audit/2023-04-footium-judging/issues/260 and https://github.com/sherlock-audit/2023-04-footium-judging/issues/77 is the duplicate of this issue as well

**Comment by hrishibhat** [comment]
Escalation accepted

Not a duplicate of #300
However not a valid issue on its own. 
_to address here is the escrow, but cannot claim the prize. But prizes are not lost/stolen. A temporary dos and can make the merkle updates to make it claimable by the owners.
There is a documentation issue that owner should be able to claim which is not checked, but that's not an issue since because merkle tree is still set by footium, nobody can 'steal'. 
Overall there is no loss of funds as such, footium can set the right recipient in the merkle tree and they can claim.

So this can be considered a low issue.

Additional Sponsor comment:
> Yep Footium can update the merkle tree to the rightful owner

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a duplicate of #300
> However not a valid issue on its own. 
> _to address here is the escrow, but cannot claim the prize. But prizes are not lost/stolen. A temporary dos and can make the merkle updates to make it claimable by the owners.
> There is a documentation issue that owner should be able to claim which is not checked, but that's not an issue since because merkle tree is still set by footium, nobody can 'steal'. 
> Overall there is no loss of funds as such, footium can set the right recipient in the merkle tree and they can claim.
> 
> So this can be considered a low issue.

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
