### ISSUE TITLE
GalloDaSballo - Can approve away their own club, getting tokens and the club stolen

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#225]
GalloDaSballo

medium

# Can approve away their own club, getting tokens and the club stolen

## Summary

Granting approvals for `FootiumClub` allows to temporarily become the owner of the club which allows stealing `FootiumPlayer`s

## Vulnerability Detail

The `FootiumEscrow` allows to grant approvals of tokens held inside of `FootiumEscrow`

If `FootiumClub` is ever borrowed, even temporarily, for example via a flashloan, then the temporary owner will be able to bypass the check for ownership and they'll be able to grant approvals from the `FootiumEscrow` for all `FootiumPlayer`s

## Impact

Loss of players

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L95-L96

```solidity
        erc721Contract.setApprovalForAll(to, approved);

```

Even by just having the ability to transfer, even if temporarily, the escrow will read a new owner, allowing to sweep away the players

## Tool used

Manual Review

## Recommendation

It may be best for Owners to self-custody the `FootiumPlayers` as a way to avoid them getting their NFTs stolen via gotchas

**Comment by Shogoki** [comment]
Escalate for 10 USDC

I think this is not a valid duplicate and should be excluded. 
The report is about borrowing a Club NFT, where the receiver can steal from the actual Owner. 
As there is no borrowing of clubs implemented, nor mentioned in the docs, i think this one is invalid.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this is not a valid duplicate and should be excluded. 
> The report is about borrowing a Club NFT, where the receiver can steal from the actual Owner. 
> As there is no borrowing of clubs implemented, nor mentioned in the docs, i think this one is invalid.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
I think this issue is still a valid duplicate of https://github.com/sherlock-audit/2023-04-footium-judging/issues/289 and should not be excluded, the root cause are uncleared approval when transferring

**Comment by Shogoki** [comment]
Hmm. This means just getting the root cause of a (potential) attack vector without stating a realistic attack vector is enough to get marked as a duplicate for an issue of others that actually detected and described the possible attack & impact

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Not a duplicate of #289 
The issue does not clearly point towards a valid attack as opposed to duplicates. 
Valid point raised in the escalation.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low
> Not a duplicate of #289 
> The issue does not clearly point towards a valid attack as opposed to duplicates. 
> Valid point raised in the escalation.
> 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
