### ISSUE TITLE
Sulpiride - Escrow allows the owner to be smart contract wallet but doesn't allow signing messages

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#229]
Sulpiride

medium

# Escrow allows the owner to be smart contract wallet but doesn't allow signing messages

## Summary
FootiumEscrow's owner can be set to a smart contract wallet, but it will not allow it to sign messages since `isValidSignature` implements only ECDSA signature check

## Vulnerability Detail
FootiumEscrow is a in-game wallet that allows club owners to manage their players. FootiumEscrow contract is IERC1271 compliant and has `isValidSignature`, but it only implements ECDSA signature. FootiumClub NFT can be minted and transferred to a smart contract wallet. Many popular smart contract wallets implement their own cryptography for signature validation that is different from ECDSA, e.g. [Safe (previously Gnosis Safe)](https://docs.safe.global/learn/safe-core/safe-core-protocol/signatures), [Etherspot](https://etherspot.io/), [Biconomy](https://www.biconomy.io/), [Soul Wallet](https://www.soulwallet.io/) and many many more

## Impact
Supporting only ECDSA will prevent most of the smart contract wallets from managing their Escrow contract and, if FootiumClub NFT is minted to a smart contract wallet, the wallet will be forced to transfer the ownership to a EOA contract

## Code Snippet
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L53-L66
```solidity
function isValidSignature(bytes32 hash, bytes memory signature)
  external
  view
  returns (bytes4 magicValue)
{
  if (
    ECDSA.recover(hash, signature) ==
    IERC721(footiumClubAddress).ownerOf(clubId)
  ) {
    return MAGICVALUE;
  }

  return 0xffffffff;
}
```

## Tool used

Manual Review

## Recommendation
Recommend using OpenZeppelin's SignatureChecker in `FootiumEscrow.isValidSignature` - https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol

If Escrow's owner is a smart contract wallet `SignatureChecker` will call it's `isValidSignature` which is a correct way to handle signatures

```solidity
function isValidSignature(bytes32 hash, bytes memory signature)
  external
  view
  returns (bytes4 magicValue)
{
  address owner = IERC721(footiumClubAddress).ownerOf(clubId);
  if (SignatureChecker.isValidSignatureNow(owner, hash, signature)) {
    return MAGICVALUE;
  }
  return 0xffffffff;
}
```

**Comment by 0xSulpiride** [comment]
Escalate for 10 USDC.

I believe this is a valid issue because it can potentially prevent many smart contracts wallets from using Footium.

Actually, even if the SCW (smart contract wallet) is using ECDSA, it still won't able to use the Footium Escrow, because the actual signer is the owner of the SCW, not the SCW itself.

Consider one of the most popular SCW's - Safe wallet.
https://github.com/safe-global/safe-contracts/blob/main/contracts/handler/CompatibilityFallbackHandler.sol#L28-L39

Escrow's `isValidSignature` should call the same method of SCW

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> I believe this is a valid issue because it can potentially prevent many smart contracts wallets from using Footium.
> 
> Actually, even if the SCW (smart contract wallet) is using ECDSA, it still won't able to use the Footium Escrow, because the actual signer is the owner of the SCW, not the SCW itself.
> 
> Consider one of the most popular SCW's - Safe wallet.
> https://github.com/safe-global/safe-contracts/blob/main/contracts/handler/CompatibilityFallbackHandler.sol#L28-L39
> 
> Escrow's `isValidSignature` should call the same method of SCW
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xSulpiride** [comment]
Have a look at this too:
https://twitter.com/safe/status/1660677975669633024

Safe users won't be able to use this feature on Footium's NFTs

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
This issue has an impact that can be considered low

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> This issue has an impact that can be considered low

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
