### ISSUE TITLE
juancito - Some ERC20 tokens can get permanently stuck in the contract due to use of `transfer()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#252]
juancito

high

# Some ERC20 tokens can get permanently stuck in the contract due to use of `transfer()`

## Summary

Some popular tokens like USDT do not return any value when they perform a `transfer()`.

This breaks the compatibility with the `IERC20` interface, which will end up reverting the functions that use it.

## Vulnerability Detail

`FootiumEscrow::transferERC20()` makes use of `transfer()` to transfer tokens out of the contract. `FootiumEscrow` is not upgradeable, so tokens transferred to it, won't be able to be recovered:

```solidity
    function transferERC20(
        IERC20 erc20Contract,
        address to,
        uint256 amount
    ) external onlyClubOwner {
        erc20Contract.transfer(to, amount); // @audit
    }
```

`FootiumPrizeDistributor::claimERC20Prize()` uses it to distribute prizes. `FootiumPrizeDistributor` is upgradeable, so tokens would be able to be distributed after a fix and an upgrade.

```solidity
    function claimERC20Prize(
        address _to,
        IERC20Upgradeable _token,
        uint256 _amount,
        bytes32[] calldata _proof
    ) external whenNotPaused nonReentrant {
        if (_to != msg.sender) {
            revert InvalidAccount();
        }

        if (
            !MerkleProofUpgradeable.verify(
                _proof,
                erc20MerkleRoot,
                keccak256(abi.encodePacked(_token, _to, _amount))
            )
        ) {
            revert InvalidERC20MerkleProof();
        }

        uint256 value = _amount - totalERC20Claimed[_token][_to];

        if (value > 0) {
            totalERC20Claimed[_token][_to] += value;
            _token.transfer(_to, value); // @audit
        }

        emit ClaimERC20(_token, _to, value);
    }
```

## Impact

Permanently stuck ERC20 tokens in `FootiumEscrow` contracts.

Temporarily stuck ERC20 tokens in `FootiumPrizeDistributor` until an upgrade is made.

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L110

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L130

## Tool used

Manual Review

## Recommendation

Use `safeTransfer` instead of `transfer`. This way, tokens that do not return any value will succeed in transfering the assets.

Duplicate of #14

**Comment by 0xJuancito** [comment]
Escalate for 10 USDC

This issue should be a duplicate of #14. 

They address the same root issue, with the same impact and mitigation.

In the case of #14: 

> Some tokens do not return a bool on ERC20 methods and use IERC20 token interface will revert transaction

In this issue:

>Some popular tokens like USDT do not return any value when they perform a transfer().
> This breaks the compatibility with the IERC20 interface, which will end up reverting the functions that use it.

It was marked as a duplicate of #86 which has a different root cause, and an opposite consequence of not reverting:

> Users can call claimERC20Prize() without actually receiving tokens if a no-revert-on-failure token is used, causing a portion of their claimable tokens to become unclaimable.

In short, the issues I escalate as duplicates both have the root cause of the **tx being reverted due to the incompatibility with the IERC20 interface** vs the one originally marked as duplicate of **no-revert-on-failure token**

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue should be a duplicate of #14. 
> 
> They address the same root issue, with the same impact and mitigation.
> 
> In the case of #14: 
> 
> > Some tokens do not return a bool on ERC20 methods and use IERC20 token interface will revert transaction
> 
> In this issue:
> 
> >Some popular tokens like USDT do not return any value when they perform a transfer().
> > This breaks the compatibility with the IERC20 interface, which will end up reverting the functions that use it.
> 
> It was marked as a duplicate of #86 which has a different root cause, and an opposite consequence of not reverting:
> 
> > Users can call claimERC20Prize() without actually receiving tokens if a no-revert-on-failure token is used, causing a portion of their claimable tokens to become unclaimable.
> 
> In short, the issues I escalate as duplicates both have the root cause of the **tx being reverted due to the incompatibility with the IERC20 interface** vs the one originally marked as duplicate of **no-revert-on-failure token**

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Valid duplication of https://github.com/sherlock-audit/2023-04-footium-judging/issues/14

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #14

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #14 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
