### ISSUE TITLE
juancito - `claimETHPrize` and `claimERC20Prize` are claimable by the receiver instead of club owners

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#260]
juancito

medium

# `claimETHPrize` and `claimERC20Prize` are claimable by the receiver instead of club owners

## Summary

The [Footium Prize Distributor Documentation](https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/technical-docs/FootiumPrizeDistributor.md#claimerc20prizeaddress-_to-ierc20upgradeable-_token-uint256-_amount-bytes32-calldata-_proof) for `claimERC20Prize()` and `claimETHPrize` states: 

> The function checks to see whether the function caller owns the club that they're claiming prizes for. If successful, the function transfers ETH / ERC20 tokens to the prize receiver account address.

The receiver might be a smart contract not prepared to claim the tokens, as the described behavior by the documentation is that the club owner would be the one performing the claim.

## Vulnerability Detail

The claim functions check `_to != msg.sender` to validate the receiver, instead of checking if they are the club owner:

```solidity
    function claimERC20Prize(
        address _to,
        IERC20Upgradeable _token,
        uint256 _amount,
        bytes32[] calldata _proof
    ) external whenNotPaused nonReentrant {
        if (_to != msg.sender) { // @audit
            revert InvalidAccount();
        }

        if (
            !MerkleProofUpgradeable.verify(
                _proof,
                erc20MerkleRoot,
                keccak256(abi.encodePacked(_token, _to, _amount))
            )
        ) {
            revert InvalidERC20MerkleProof();
        }

        uint256 value = _amount - totalERC20Claimed[_token][_to];

        if (value > 0) {
            totalERC20Claimed[_token][_to] += value;
            _token.transfer(_to, value);
        }

        emit ClaimERC20(_token, _to, value);
    }
```

## Impact

Tokens and Ether prizes might be unclaimable if the receiver is not prepared to do so, considering that the expected behavior is that the club owner should be the responsible to do so.

If a club owner changes, the assets are claimable by the original receiver, and not for the club (via its owner).

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L106-L134

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L144-L175

## Tool used

Manual Review

## Recommendation

Validate that the `msg.sender` is the club owner, as described in the documentation. This also allows the club owner to specify any address where they would like to receive the assets.

Here's an example for `claimERC20Prize()`. A similar implementation should be also done for `claimERC20Prize()`.

```diff
    function claimERC20Prize(
+       uint256 _clubId,
        address _to,
        IERC20Upgradeable _token,
        uint256 _amount,
        bytes32[] calldata _proof
    ) external whenNotPaused nonReentrant {
-       if (_to != msg.sender) {
-            revert InvalidAccount();
-        }
+       if (msg.sender != IERC721(footiumClubAddress).ownerOf(_clubId)) {
+           revert NotClubOwner(_clubId, msg.sender);
+       }

        if (
            !MerkleProofUpgradeable.verify(
                _proof,
                erc20MerkleRoot,
-               keccak256(abi.encodePacked(_token, _to, _amount))
+               keccak256(abi.encodePacked(_token, _clubId, _amount))
            )
        ) {
            revert InvalidERC20MerkleProof();
        }

-       uint256 value = _amount - totalERC20Claimed[_token][_to];
+       uint256 value = _amount - totalERC20Claimed[_token][_clubId];

        if (value > 0) {
-           totalERC20Claimed[_token][_to] += value;
+           totalERC20Claimed[_token][_clubId] += value;
            _token.transfer(_to, value);
        }

        emit ClaimERC20(_token, _to, value);
    }
```

**Comment by 0xJuancito** [comment]
Escalate for 10 USDC

I would like to request a review of this issue and consider it `Valid` and `High`.

In its impact section this issue addresses a `High` severity:

> If a club owner changes, the assets are claimable by the original receiver, and not for the club (via its owner).

Other issues have been addresses as `Valid` and `High` as well for the same impact. Allowing the former club to take funds when clubs are transferred or sold. Examples:
- #289
- #291

In this case, the same issue araises: a club can be sold at some higher price, showing that it has a pending prize that has not been claimed.

On top of that, this **issue addresses the expected behavior** described in the [documentation](https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/technical-docs/FootiumPrizeDistributor.md#claimerc20prizeaddress-_to-ierc20upgradeable-_token-uint256-_amount-bytes32-calldata-_proof), while providing a coded mitigation that is easy to implement.

> The function checks to see whether the function caller **owns the club** that they're claiming prizes for.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I would like to request a review of this issue and consider it `Valid` and `High`.
> 
> In its impact section this issue addresses a `High` severity:
> 
> > If a club owner changes, the assets are claimable by the original receiver, and not for the club (via its owner).
> 
> Other issues have been addresses as `Valid` and `High` as well for the same impact. Allowing the former club to take funds when clubs are transferred or sold. Examples:
> - #289
> - #291
> 
> In this case, the same issue araises: a club can be sold at some higher price, showing that it has a pending prize that has not been claimed.
> 
> On top of that, this **issue addresses the expected behavior** described in the [documentation](https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/technical-docs/FootiumPrizeDistributor.md#claimerc20prizeaddress-_to-ierc20upgradeable-_token-uint256-_amount-bytes32-calldata-_proof), while providing a coded mitigation that is easy to implement.
> 
> > The function checks to see whether the function caller **owns the club** that they're claiming prizes for.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

I agree that this issue should be reevaluated. Additionally, https://github.com/sherlock-audit/2023-04-footium-judging/issues/77 should be included as a duplicate of this.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I agree that this issue should be reevaluated. Additionally, https://github.com/sherlock-audit/2023-04-footium-judging/issues/77 should be included as a duplicate of this.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by RobocopSR** [comment]
Escalate for 10 USDC

This escalation is to contra-argument Watson Juancito's Escalation. 

The current implementation is correct, if `_to` is a smart contract which cannot handle the tokens will be a user mistake.

Actually the mitigation proposed by Juancito, where the prize is hold for the owner of `clubID` opens the attack vectors (not close them) where: 

1.- Attacker puts to sell a `clubID` with pending prizes.
2.- Victim sends buy transaction
3.- Attacker front runs and claim the prizes
4. Victim bought the club at an inflated prize thinking it had pending prizes.

At the best this is an informational issue to update the documentation. But the implementation is correct since prices won should be claimed by the account who participated, regardless if it is still the owner of the club. Making the prizes to be claimed by club owner (as recommended by the Watson) open the attack vector described above.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This escalation is to contra-argument Watson Juancito's Escalation. 
> 
> The current implementation is correct, if `_to` is a smart contract which cannot handle the tokens will be a user mistake.
> 
> Actually the mitigation proposed by Juancito, where the prize is hold for the owner of `clubID` opens the attack vectors (not close them) where: 
> 
> 1.- Attacker puts to sell a `clubID` with pending prizes.
> 2.- Victim sends buy transaction
> 3.- Attacker front runs and claim the prizes
> 4. Victim bought the club at an inflated prize thinking it had pending prizes.
> 
> At the best this is an informational issue to update the documentation. But the implementation is correct since prices won should be claimed by the account who participated, regardless if it is still the owner of the club. Making the prizes to be claimed by club owner (as recommended by the Watson) open the attack vector described above.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Accepting @0xRobocop's escalation. There are no funds at risk and the merkle proofs can be easily generated using the club owner's address. As pointed out making the suggested changes opens up to more issues. 
Valid low issue

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low
> Accepting @0xRobocop's escalation. There are no funds at risk and the merkle proofs can be easily generated using the club owner's address. As pointed out making the suggested changes opens up to more issues. 
> Valid low issue

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
