### ISSUE TITLE
Phantasmagoria - Have to be approved to zero first

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#307]
Phantasmagoria

medium

# Have to be approved to zero first

## Summary
Have to be approved to zero first

## Vulnerability Detail
Some ERC20 tokens like USDT require resetting the approval to 0 first before being able to reset it to another value.
The erc20Contract.approve function does not do this.

## Impact
Unsafe ERC20 approve that do not handle non-standard erc20 behavior.
1.Some token contracts do not return any value.
2.Some token contracts revert the transaction when the allowance is not zero.

## Code Snippet
```solidity
function setApprovalForERC20(
        IERC20 erc20Contract,
        address to,
        uint256 amount
    ) external onlyClubOwner {
        erc20Contract.approve(to, amount);
    }
```
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L75-L81
## Tool used

Manual Review

## Recommendation
It is recommended to set the allowance to zero before increasing the allowance and use `safeApprove`

**Comment by Phantasmagoria13** [comment]
Escalate for 10 USD
I kindly request that the finding be escalated for further review. Based on my analysis, I think this finding is a duplicate of issue #82.

In my assessment, I pointed out the problematic nature of using the ERC20 approve function for two reasons. Firstly, certain token contracts do not provide any return value when the function is executed. Secondly, some token contracts revert the transaction if the allowance is not set to zero.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USD
> I kindly request that the finding be escalated for further review. Based on my analysis, I think this finding is a duplicate of issue #82.
> 
> In my assessment, I pointed out the problematic nature of using the ERC20 approve function for two reasons. Firstly, certain token contracts do not provide any return value when the function is executed. Secondly, some token contracts revert the transaction if the allowance is not set to zero.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Escalation is valid

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #86

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #86 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
