### ISSUE TITLE
cuthalion0x - `FootiumClub` may mint tokens to a contract which is incapable of handling them

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#333]
cuthalion0x

medium

# `FootiumClub` may mint tokens to a contract which is incapable of handling them

## Summary

`FootiumClub.safeMint` invokes `ERC721Upgradeable._mint` instead of `ERC721Upgradeable._safeMint`. If the recipient address is a contract, the newly minted tokens may be stuck.

## Vulnerability Detail

`ERC721Upgradeable._safeMint` contains safety checks to determine if the recipient address is a smart contract and if so, whether it implements the `IERC721ReceiverUpgradeable` interface. These checks ensure that the recipient is prepared to handle ERC721 tokens so that they do not get locked in a naive contract.

However, `FootiumClub.safeMint` uses the plain `ERC721Upgradeable._mint`, which does not contain such checks. If the `_to` address is an unwitting smart contract, the minted tokens will be stuck.

## Impact

Newly minted `FootiumClub` tokens could be lost forever to unprepared smart contract recipients.

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/11736f3f7f7efa88cb99ee98b04b85a46621347c/footium-eth-shareable/contracts/FootiumClub.sol#L51-L68

```solidity
    /** @notice Mints a Footium football club
     * @dev Only accounts with the minting role can mint new clubs.
     * @param to The address that will receive the club.
     * @param tokenId The ID of the club to be minted.
     */
    function safeMint(address to, uint256 tokenId)
        external
        onlyRole(MINTER_ROLE)
        nonReentrant
        whenNotPaused
    {
        FootiumEscrow escrow = new FootiumEscrow(address(this), tokenId);
        clubToEscrow[tokenId] = escrow;

        _mint(to, tokenId);

        emit EscrowDeployed(tokenId, escrow);
    }
```

## Tool used

Manual Review

## Recommendation

Change `_mint` to `_safeMint`.

Duplicate of #342

**Comment by cuthalion0x** [comment]
Escalate for 10 USDC
I think this is wrongly classified as invalid. It should be a duplicate of #342 instead. It describes the same discrepancy between `_mint` and `_safeMint` as well as the potential for minting to a contract which doesn't properly handle NFTs.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I think this is wrongly classified as invalid. It should be a duplicate of #342 instead. It describes the same discrepancy between `_mint` and `_safeMint` as well as the potential for minting to a contract which doesn't properly handle NFTs.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Escalation is valid.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #342

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #342 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
