### ISSUE TITLE
innertia - ERC20 of Missing Return Values causes tokens to get stuck

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#48]
innertia

high

# ERC20 of Missing Return Values causes tokens to get stuck

## Summary
Some tokens do not return a bool (e.g. `USDT`, `BNB`, `OMG`) on ERC20 methods.
These tokens can be sent to the contract, but cannot be retrieved by the transfer function, resulting in a stack of assets.
## Vulnerability Detail
`FootiumEscrow`'s `transferERC20` calls `erc20Contract.transfer(to, amount)`.
`FootiumPrizeDistributor`'s `claimERC20Prize` calls `_token.transfer(_to, value)`.
Both use ERC20 transfer and attempt to transfer the token outside of the contract, but an error occurs and the transfer always fails.
## Impact
Tokens stack forever.
## Code Snippet
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L110
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L130
## Tool used

Manual Review

## Recommendation
Use `safeTransfer`.

**Comment by innertiaJP** [comment]
Escalate for 10 USDC

This report is about ERC20 tokens does not return bool from some methods and overlaps with the following issue.
https://github.com/sherlock-audit/2023-04-footium-judging/issues/14

In particular, the claims are completely consistent with these reports.
https://github.com/sherlock-audit/2023-04-footium-judging/issues/72
https://github.com/sherlock-audit/2023-04-footium-judging/issues/118

Therefore, this report should be treated the same as these.

**Comment by ctf-sec** [comment]
Valid escalation, can be a duplicate of 72

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #14

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #14

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
