### ISSUE TITLE
14si2o_Flint - [M-01] Did not Approve to zero first

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#58]
14si2o_Flint

medium

# [M-01] Did not Approve to zero first

medium

## Summary

In the contest Q&A, the Footium protocol states that they expect to be able to interact with any ERC20 tokens. However, they do not anticipate the behavior of non-standard erc20 tokens which require resetting approval to 0 before changing it.  

## Vulnerability Detail

Some ERC20 tokens (like USDT) do not work when changing the allowance from an existing non-zero allowance value. For example Tether (USDT)'s ` approve() ` function will revert if the current approval is not zero, to protect against front-running changes of approvals.

The `erc20Contract.approve(to, amount)` in FootiumEscrow does not reset the approval to 0 before setting it to another value. 

## Impact

Unsafe ERC20 approve that does not handle non-standard erc20 behavior.
1.Some token contracts do not return any value.
2.Some token contracts revert the transaction when the allowance is not zero.

## Code Snippet

https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L75-L81

## Tool used

Manual Review

## Recommendation
It is recommended to set the allowance to zero before increasing the allowance and use safeApprove/safeIncreaseAllowance from OpenZeppelin's safeApprove implementation.

Duplicate of #86

**Comment by 14si2o** [comment]
Escalate for 10 USDC

I believe this  is a valid duplicate of https://github.com/sherlock-audit/2023-04-footium-judging/issues/82

In the finding I describe that using the ERC20 approve function is problematic since 1. some token contracts do not return any value and 2. some token revert the transaction when the allowance is not zero.

The finding was excluded since was not expansive enough on the details of Impact 1. (no return value). I discussed this with head judge **ladboy233** and he suggested I escalate this is a valid duplicate. 

So I would kindly request that the finding to be judged valid as a duplicate of issue #82

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I believe this  is a valid duplicate of https://github.com/sherlock-audit/2023-04-footium-judging/issues/82
> 
> In the finding I describe that using the ERC20 approve function is problematic since 1. some token contracts do not return any value and 2. some token revert the transaction when the allowance is not zero.
> 
> The finding was excluded since was not expansive enough on the details of Impact 1. (no return value). I discussed this with head judge **ladboy233** and he suggested I escalate this is a valid duplicate. 
> 
> So I would kindly request that the finding to be judged valid as a duplicate of issue #82

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Valid duplication of https://github.com/sherlock-audit/2023-04-footium-judging/issues/82

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #86

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #86 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
