### ISSUE TITLE
Dug - By only supporting `setApprovalForAll`, escrow NFTs are exposed to unnecessary risk

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#69]
Dug

medium

# By only supporting `setApprovalForAll`, escrow NFTs are exposed to unnecessary risk

## Summary
The `FootiumEscrow` contract only supports the `setApprovalForAll` function. This means that escrow NFTs are exposed to unnecessary risk because entire collections become available for transfer instead of individual NFTs. 

## Vulnerability Detail
The ERC-721 standard defines two functions for managing approvals: `approve` and `setApprovalForAll`. `approve` allows for an individual NFT to be approved for transfer. `setApprovalForAll` allows for an entire collection of NFTs to be approved for transfer.

Generally, `approve` is used to limit exposure to risk. For example, if a user wants to sell an NFT on a secondary market, they would only approve that NFT for transfer. This means that if the secondary market is compromised, only that NFT is at risk.

The `FootiumEscrow` contract only supports `setApprovalForAll`. This means that the only option for owners is to approve the entire collection for transfer. This is a problem because it exposes all NFT in that collection to unnecessary risk.

## Impact
Escrow NFTs are exposed to unnecessary risk. An owner can loose entire collections of NFTs if they interact with a malicious contract or if a secondary market is compromised.

## Code Snippet
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumEscrow.sol#L90-L96

## Tool used
Manual Review

## Recommendation
Include wrappers for the standard ERC-721 `approve` function, enabling individual NFTs to be approved for transfer.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

This issue should be considered a valid medium. A user should not be required to issue approvals for their entire collection when the ERC-721 spec provides the ability to approve individual NFTs. This reduces overall security and opens up an obvious attack vector.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue should be considered a valid medium. A user should not be required to issue approvals for their entire collection when the ERC-721 spec provides the ability to approve individual NFTs. This reduces overall security and opens up an obvious attack vector.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
The impact is not severe enough to be considered as a medium

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
While this is a valid security suggestion, this can be considered low/informational.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> While this is a valid security suggestion, this can be considered low/informational. 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
